/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      // Módulo condominios → puerto 8003
      { source: '/api/biometrico/:path*', destination: 'http://backend-condominios:8003/api/biometrico/:path*' },
      { source: '/api/biometrico', destination: 'http://backend-condominios:8003/api/biometrico' },
      { source: '/api/condominios/:path*', destination: 'http://backend-condominios:8003/api/condominios/:path*' },
      { source: '/api/torres/:path*',      destination: 'http://backend-condominios:8003/api/torres/:path*' },
      { source: '/api/pisos/:path*',       destination: 'http://backend-condominios:8003/api/pisos/:path*' },
      { source: '/api/departamentos/:path*', destination: 'http://backend-condominios:8003/api/departamentos/:path*' },
      { source: '/api/personas/:path*',    destination: 'http://backend-condominios:8003/api/personas/:path*' },
      { source: '/api/finanzas/:path*',    destination: 'http://backend-condominios:8003/api/finanzas/:path*' },
      { source: '/api/rrhh/:path*',        destination: 'http://backend-condominios:8003/api/rrhh/:path*' },
      { source: '/api/admin/tenants/:path*', destination: 'http://backend-condominios:8003/api/admin/tenants/:path*' },
      { source: '/api/admin/tenants',      destination: 'http://backend-condominios:8003/api/admin/tenants' },
      // Superadmin
      { source: "/api/cron/:path*", destination: "http://backend-condominios:8003/api/cron/:path*" },
        { source: "/api/superadmin/:path*", destination: "http://backend-condominios:8003/api/superadmin/:path*" },
      { source: "/api/cron/:path*", destination: "http://backend-condominios:8003/api/cron/:path*" },
        { source: "/api/superadmin", destination: "http://backend-condominios:8003/api/superadmin" },
      // Portal residente + historial
      { source: "/api/accesos/:path*", destination: "http://backend-condominios:8003/api/accesos/:path*" },
      { source: "/api/portal/:path*",      destination: "http://backend-condominios:8003/api/portal/:path*" },
      { source: "/api/historial/:path*",   destination: "http://backend-condominios:8003/api/historial/:path*" },
      { source: "/api/historial",          destination: "http://backend-condominios:8003/api/historial" },
      // Login/auth condominios → 8003
      { source: '/api/login',              destination: 'http://backend-condominios:8003/api/login' },
      { source: '/api/auth/:path*',        destination: 'http://backend-condominios:8003/api/auth/:path*' },
            { source: '/api/reservas', destination: 'http://backend-condominios:8003/api/reservas' },
      { source: '/api/reservas/:path*', destination: 'http://backend-condominios:8003/api/reservas/:path*' },
      { source: '/api/rrhh', destination: 'http://backend-condominios:8003/api/rrhh' },
      { source: '/api/avisos/:path*', destination: 'http://backend-condominios:8003/api/avisos/:path*' },
      { source: '/api/avisos', destination: 'http://backend-condominios:8003/api/avisos' },
      { source: '/api/votaciones/:path*', destination: 'http://backend-condominios:8003/api/votaciones/:path*' },
      { source: '/api/votaciones', destination: 'http://backend-condominios:8003/api/votaciones' },
      { source: '/api/incidencias/:path*', destination: 'http://backend-condominios:8003/api/incidencias/:path*' },
      { source: '/api/incidencias', destination: 'http://backend-condominios:8003/api/incidencias' },
      { source: '/api/puertas/:path*', destination: 'http://backend-condominios:8003/api/puertas/:path*' },
      { source: '/api/puertas', destination: 'http://backend-condominios:8003/api/puertas' },
      { source: '/api/rfid/:path*', destination: 'http://backend-condominios:8003/api/rfid/:path*' },
      { source: '/api/rfid', destination: 'http://backend-condominios:8003/api/rfid' },
      { source: '/api/personal/:path*', destination: 'http://backend-condominios:8003/api/personal/:path*' },
      { source: '/api/personal', destination: 'http://backend-condominios:8003/api/personal' },
      { source: '/api/usuarios/:path*', destination: 'http://backend-condominios:8003/api/usuarios/:path*' },
      { source: '/api/usuarios', destination: 'http://backend-condominios:8003/api/usuarios' },
      // Base paths (no trailing slash) → condominios
      { source: '/api/personas', destination: 'http://backend-condominios:8003/api/personas' },
      { source: '/api/condominios', destination: 'http://backend-condominios:8003/api/condominios' },
      { source: '/api/finanzas', destination: 'http://backend-condominios:8003/api/finanzas' },
      { source: '/api/accesos', destination: 'http://backend-condominios:8003/api/accesos' },
      { source: '/api/historial', destination: 'http://backend-condominios:8003/api/historial' },
      { source: '/api/admin/tenants', destination: 'http://backend-condominios:8003/api/admin/tenants' },
      { source: '/api/visitas/:path*', destination: 'http://backend-condominios:8003/api/visitas/:path*' },
      { source: '/api/visitas', destination: 'http://backend-condominios:8003/api/visitas' },
      { source: '/api/estacionamientos/:path*', destination: 'http://backend-condominios:8003/api/estacionamientos/:path*' },
      { source: '/api/estacionamientos', destination: 'http://backend-condominios:8003/api/estacionamientos' },
      { source: '/api/paqueteria/:path*', destination: 'http://backend-condominios:8003/api/paqueteria/:path*' },
      { source: '/api/paqueteria', destination: 'http://backend-condominios:8003/api/paqueteria' },
      { source: '/api/admin-users/:path*', destination: 'http://backend-condominios:8003/api/admin-users/:path*' },
      { source: '/api/facial/:path*', destination: 'http://backend-condominios:8003/api/facial/:path*' },
      { source: '/api/facial', destination: 'http://backend-condominios:8003/api/facial' },
      { source: '/api/admin-users', destination: 'http://backend-condominios:8003/api/admin-users' },
      { source: '/api/conserje/:path*', destination: 'http://backend-condominios:8003/api/conserje/:path*' },
      { source: '/api/conserje', destination: 'http://backend-condominios:8003/api/conserje' },
      { source: '/api/alertas-sistema/:path*', destination: 'http://backend-condominios:8003/api/alertas-sistema/:path*' },
      { source: '/api/alertas-sistema', destination: 'http://backend-condominios:8003/api/alertas-sistema' },
      { source: '/api/push/:path*', destination: 'http://backend-condominios:8003/api/push/:path*' },
      { source: '/api/push', destination: 'http://backend-condominios:8003/api/push' },
      { source: '/api/scanner/:path*', destination: 'http://backend-condominios:8003/api/scanner/:path*' },
      { source: '/api/scanner', destination: 'http://backend-condominios:8003/api/scanner' },
      { source: '/api/migracion/:path*', destination: 'http://backend-condominios:8003/api/migracion/:path*' },
      { source: '/api/migracion', destination: 'http://backend-condominios:8003/api/migracion' },
      { source: '/api/gastos-comunes/:path*', destination: 'http://backend-condominios:8003/api/gastos-comunes/:path*' },
      { source: '/api/gastos-comunes', destination: 'http://backend-condominios:8003/api/gastos-comunes' },
      { source: '/api/multas/:path*', destination: 'http://backend-condominios:8003/api/multas/:path*' },
      { source: '/api/multas', destination: 'http://backend-condominios:8003/api/multas' },
      { source: '/api/mascotas/:path*', destination: 'http://backend-condominios:8003/api/mascotas/:path*' },
      { source: '/api/mascotas', destination: 'http://backend-condominios:8003/api/mascotas' },
      { source: '/api/proveedores/:path*', destination: 'http://backend-condominios:8003/api/proveedores/:path*' },
      { source: '/api/proveedores', destination: 'http://backend-condominios:8003/api/proveedores' },
      { source: '/api/checklist/:path*', destination: 'http://backend-condominios:8003/api/checklist/:path*' },
      { source: '/api/checklist', destination: 'http://backend-condominios:8003/api/checklist' },
      { source: '/api/noc/:path*', destination: 'http://backend-condominios:8003/api/noc/:path*' },
      { source: '/api/noc', destination: 'http://backend-condominios:8003/api/noc' },
      { source: '/api/wa/:path*', destination: 'http://backend-condominios:8003/api/wa/:path*' },
      { source: '/api/wa', destination: 'http://backend-condominios:8003/api/wa' },
      { source: '/api/pagos/:path*', destination: 'http://backend-condominios:8003/api/pagos/:path*' },
      { source: '/api/pagos', destination: 'http://backend-condominios:8003/api/pagos' },
      { source: '/api/admin/integraciones/:path*', destination: 'http://backend-condominios:8003/api/admin/integraciones/:path*' },
      { source: '/api/admin/integraciones', destination: 'http://backend-condominios:8003/api/admin/integraciones' },
            { source: '/api/ia/:path*', destination: 'http://backend-condominios:8003/api/ia/:path*' },
      { source: '/api/ia', destination: 'http://backend-condominios:8003/api/ia' },
      { source: '/api/anomalias/:path*', destination: 'http://backend-condominios:8003/api/anomalias/:path*' },
      { source: '/api/anomalias', destination: 'http://backend-condominios:8003/api/anomalias' },
      { source: '/api/resumenes/:path*', destination: 'http://backend-condominios:8003/api/resumenes/:path*' },
      { source: "/api/resumenes", destination: "http://backend-condominios:8003/api/resumenes" },
      { source: "/api/reportes/:path*", destination: "http://backend-condominios:8003/api/reportes/:path*" },
      { source: "/api/reportes", destination: "http://backend-condominios:8003/api/reportes" },
      { source: "/api/sii/:path*", destination: "http://backend-condominios:8003/api/sii/:path*" },
      { source: "/api/sii", destination: "http://backend-condominios:8003/api/sii" },
      { source: '/api/sistema/:path*', destination: 'http://backend-condominios:8003/api/sistema/:path*' },
      { source: '/api/sistema', destination: 'http://backend-condominios:8003/api/sistema' },
      { source: '/api/camaras/:path*', destination: 'http://backend-condominios:8003/api/camaras/:path*' },
      { source: '/api/camaras', destination: 'http://backend-condominios:8003/api/camaras' },
      { source: '/api/alarmas/:path*', destination: 'http://backend-condominios:8003/api/alarmas/:path*' },
      { source: '/api/alarmas', destination: 'http://backend-condominios:8003/api/alarmas' },
      // Módulo core ventas → puerto 8006
      { source: '/uploads/:path*', destination: 'http://backend-condominios:8003/uploads/:path*' },
      { source: '/api/:path*',             destination: 'http://backend-core:8006/:path*' },
    ]
  },
  images: {
    domains: ['conectaai.cl', 'localhost'],
  },
  output: 'standalone',
}

module.exports = nextConfig
